# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
pool:
  Default
steps:
- task: CmdLine@2
  name: "Pre_Command_Check"
  inputs:
    script: |
      echo Commands are running
      echo Successfully...
- task: Maven@3
  inputs:
    mavenPomFile: 'C:\Users\LENOVO\Downloads\code\demo\demo\pom.xml'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'
    allowBrokenSymlinks: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  inputs:
    SourceFolder: 'C:\Users\LENOVO\Downloads\code\demo\demo\target'
    Contents: '**.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'prashi'
    publishLocation: 'Container'
